name: 'Run Composite Action'
on: 
  push:
  workflow_dispatch:

env:
  PERSON: "Mono The Octocat"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - id: actions-say-hello
        uses: akbas-orga/actions-composite@v1
        with:
          person: ${{ env.PERSON }}
